bg:          &bg          1d2021ff
bg0:         &bg0         282828ff
bg1:         &bg1         3c3836ff
bg2:         &bg2         504945ff
bg3:         &bg3         665c54ff
bg4:         &bg4         7c6f64ff
fg:          &fg          ebdbb2ff
fg0:         &fg0         fbf1c7ff
fg1:         &fg1         ebdbb2ff
fg2:         &fg2         d5c4a1ff
fg3:         &fg3         bdae93ff
fg4:         &fg4         a89984ff
gray:        &gray        928374ff
red:         &red         cc241dff
red_bold:    &red_bold    fb4934ff
orange:      &orange      d65d0eff
orange_bold: &orange_bold fe8019ff
yellow:      &yellow      d79921ff
yellow_bold: &yellow_bold fabd2fff
green:       &green       98971aff
green_bold:  &green_bold  b8bb26ff
aqua:        &aqua        689d6aff
aqua_bold:   &aqua_bold   8ec07cff
blue:        &blue        458588ff
blue_bold:   &blue_bold   83a598ff
purple:      &purple      b16286ff
purple_bold: &purple_bold d3869bff

bar:
  height: 16
  location: bottom
  font: hack:pixelsize=14:style=bold
  spacing: 0
  margin: 0
  layer: bottom
  foreground: *fg
  background: *bg1

  left:
    - river:
        title: {string: {text: " {title}"}}
        anchors:
          - base: &river_base
              left-margin: 8
              right-margin: 8
              default: {string: {text: }}
              conditions:
                id == 1: {string: {text: 1}}
                id == 2: {string: {text: 2}}
                id == 3: {string: {text: 3}}
                id == 4: {string: {text: 4}}
                id == 5: {string: {text: 5}}
                id == 6: {string: {text: 6}}
                id == 7: {string: {text: 7}}
                id == 8: {string: {text: 8}}
                id == 9: {string: {text: 9}}

        content:
          map:
            on-click:
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
              middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
            conditions:
              state == urgent:
                map:
                  <<: *river_base
                  deco: {background: {color: *red_bold}}
                  foreground: *bg
              state == focused:
                map:
                  <<: *river_base
                  deco: {background: {color: *yellow_bold}}
                  foreground: *bg
              state == visible:
                map:
                  <<: *river_base
                  deco: {background: {color: *fg4}}
              state == unfocused:
                map:
                  <<: *river_base
                  deco: {background: {color: *fg4}}
                  foreground: *bg
              state == invisible && occupied: {map: {<<: *river_base}}
              state == invisible && ~occupied: {empty: {}}


  right:
    - label:
        content: {string: {text: "▐", deco: {background: {color: *bg1}}, foreground: *fg4}}
    - mpd:
        host: localhost
        port: 6600
        content:
          map:
            default:
              string: {text: ""}
            conditions:
              state == playing:
                string: {text: " ♬ {pos}/{end} {title} ", deco: {background: {color: *bg2}}, foreground: *fg}
              state == paused:
                string: {text: " ♬ {pos}/{end} {title} ", deco: {background: {color: *bg2}}, foreground: *fg}
    - pipewire:
        content:
          map:
            conditions:
              type == "sink" && ~muted && form_factor == headphones:
                - string: {text: "  {cubic_volume} ", deco: {background: {color: *bg3}}, foreground: *fg}
              type == "sink" && ~muted && form_factor == hdmi:
                - string: {text: "  {cubic_volume} ", deco: {background: {color: *bg3}}, foreground: *fg}
              type == "sink" && muted:
                - string: {text: "  {cubic_volume} ", deco: {background: {color: *bg3}}, foreground: *fg}
    - network:
        name: wlp3s0
        content:
          map:
            default:
              string: {text: " ⚠ {ssid} ", deco: {background: {color: *bg4}}, foreground: *fg}
            conditions:
              state == up:
                string: {text: "  {ssid} ", deco: {background: {color: *bg4}}, foreground: *fg}
    - clock:
        time-format: "%m/%d/%Y %I:%M:%S %P"
        content:
          - string: {text: "  {time} ", deco: {background: {color: *fg4}}, foreground: *bg}

