#!/bin/sh

reload.sh

# remove cursor when typing
xbanish &

# start authentication agent
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh) &
export SSH_AUTH_SOCK &

# start lock screen daemon
xss-lock -- i3lock -n -u -c 1c69b1 -i $XDG_PICTURES_DIR/backgrounds/blue_screen.png &

# set screen lock timeout
xset s off &

# start music daemon
mpd &

# start wm
exec dwm
