#!/bin/bash

# add displays
autorandr -c &

# load Xresources database
xrdb -load $XDG_CONFIG_HOME/Xresources &

# remap caps and tab
xmodmap $XDG_CONFIG_HOME/Xmodmap/config &
xcape -e 'Control_L=Escape;Hyper_R=Tab' &

# set key repeat
xset r rate 300 35 &

# start hotkey daemon
sxhkd &

# remove cursor when typing
xbanish &

# start authentication agent
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh) &
export SSH_AUTH_SOCK &

# start lock screen daemon
xss-lock -- i3lock -n -u -c 1c69b1 -i $XDG_PICTURES_DIR/backgrounds/blue_screen.png &

# set screen lock timeout
xset s 1200 &

# start music daemon
mpd &

# start polybar
load_polybar.sh &

# start wm
exec bspwm
