#!/bin/sh

reload.sh

# start authentication agent
#eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh) &
#export SSH_AUTH_SOCK &

# start lock screen daemon
#xss-lock -- i3lock -n -u -c 1c69b1 -i $XDG_PICTURES_DIR/backgrounds/blue_screen.png &

# set screen lock timeout
#xset s off &

# start music daemon
mpd &
mpDris2 & # add support for MPRIS
#mpc consume on

# fix audio over displayport delay problem
#mpv --pause $SCRIPTS/silent.mp3 &

#set audio levels
pactl set-sink-volume @DEFAULT_SINK@ 50%
pactl set-source-volume @DEFAULT_SOURCE@ 50%

# start clipboard daemon
clipmenud &

# start wm
exec dwm
