#!/bin/bash

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config bottom_padding       -5
bspc config top_padding          -5
bspc config left_padding         -5
bspc config right_padding        -5
