#!/bin/sh

bspc config pointer_modifier       mod3
bspc config split_ratio            0.5

# remove borders for one app
bspc config borderless_monocle     true
bspc config single_monocle         true

# borders
bspc config border_width           2
bspc config window_gap             5
bspc config bottom_padding         11
bspc config top_padding            -5
bspc config left_padding           -5
bspc config right_padding          -5

# colors
bspc config normal_border_color    "#928374"
bspc config active_border_color    "#928374"
bspc config focused_border_color   "#fabd2f"
bspc config presel_feedback_color  "#928374"

# Change the default X shaped cursor to a pointer
xsetroot -cursor_name left_ptr

# rules:
bspc rule -a Zathura state=tiled
bspc rule -a st-256color:session_options state=floating
bspc rule -a st-256color:save state=floating
bspc rule -a st-256color:ncmpcpp state=fullscreen
