# determine the name with sudo uinput -p -d /dev/input/by-id/...

- JOB: "intercept -g $DEVNODE | hkd-relayer | uinput -d $DEVNODE"
  DEVICE:
    NAME: "SEMITEK USB-HID Gaming Keyboard"
    EVENTS:
      EV_KEY: [ KEY_A ]

# GK61 keyboard
# - JOB: "intercept -g $DEVNODE | dual-function-keys -c /home/ak/.config/udevmon/gk61-kb.yaml | uinput -d $DEVNODE"
#   DEVICE:
#     NAME: "SEMITEK USB-HID Gaming Keyboard"
#     EVENTS:
#       EV_KEY: [KEY_TAB, KEY_CAPSLOCK]

# # Thinkpad Keyboard
# - JOB: "intercept -g $DEVNODE | dual-function-keys -c /home/ak/.config/udevmon/thinkpad-kb.yaml | uinput -d $DEVNODE"
#   DEVICE:
#     NAME: "AT Translated Set 2 keyboard"
#     EVENTS:
#       EV_KEY: [KEY_TAB, KEY_CAPSLOCK]

# # Thinkpad TrackPoint
# - JOB: "intercept -g $DEVNODE | dual-function-keys -c /home/ak/.config/udevmon/thinkpad-tpoint.yaml | uinput -d $DEVNODE"
#   DEVICE:
#     NAME: "TPPS/2 IBM TrackPoint"
#     EVENTS:
#       EV_KEY: [BTN_RIGHT]
