#!/bin/sh

# Use the "logo" key as the primary modifier
meta="Mod4"
alt="Mod1"

# startup
startup.sh
pkill yambar
yambar &

# Mod+Q to close the focused view
riverctl map normal $meta Q close

# Mod+E to exit river
riverctl map normal $meta+Shift Q exit

# windows
riverctl map normal $meta J focus-view next
riverctl map normal $meta K focus-view previous
riverctl map normal $meta L focus-output next
riverctl map normal $meta+Shift J swap next
riverctl map normal $meta+Shift K swap previous
riverctl map normal $meta+Shift L send-to-output next
riverctl map normal $meta Space zoom

# decrease/increase the main factor by 5%
riverctl map normal $meta Minus send-layout-cmd rivercarro "main-ratio -0.03"
riverctl map normal $meta Equal send-layout-cmd rivercarro "main-ratio +0.03"
                                ka
# Mod+Shift+H and Mod+Shift+L topk increment/decrement the number of
# main views in the layout
riverctl map normal $meta I mod-main-count +1
riverctl map normal $meta D mod-main-count -1

# Mod+Alt+{H,J,K,L} to move views
riverctl map normal $meta+$alt H move left 100
riverctl map normal $meta+$alt J move down 100
riverctl map normal $meta+$alt K move up 100
riverctl map normal $meta+$alt L move right 100

# Mod+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal $meta+$alt+Control H snap left
riverctl map normal $meta+$alt+Control J snap down
riverctl map normal $meta+$alt+Control K snap up
riverctl map normal $meta+$alt+Control L snap right

# Mod+Alt+Shif+{H,J,K,L} to resize views
riverctl map normal $meta+$alt+Shift H resize horizontal -100
riverctl map normal $meta+$alt+Shift J resize vertical 100
riverctl map normal $meta+$alt+Shift K resize vertical -100
riverctl map normal $meta+$alt+Shift L resize horizontal 100

# Mod + Left Mouse Button to move views
riverctl map-pointer normal $meta BTN_LEFT move-view

# Mod + Right Mouse Button to resize views
riverctl map-pointer normal $meta BTN_RIGHT resize-view

for i in $(seq 1 9); do
    tags=$((1 << ($i - 1)))

    # Mod+[1-9] to focus tag [0-8]
    riverctl map normal $meta $i set-focused-tags $tags

    # Mod+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal $meta+Shift $i set-view-tags $tags

    # Mod+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal $meta+Control $i toggle-focused-tags $tags

    # Mod+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal $meta+Shift+Control $i toggle-view-tags $tags
done

# Mod+0 to focus all tags
# Mod+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $meta 0 set-focused-tags $all_tags
riverctl map normal $meta+Shift 0 set-view-tags $all_tags

riverctl map normal $meta Period spawn river-shifttags
riverctl map normal $meta Comma spawn "river-shifttags --shifts -1"

# Mod+F to toggle fullscreen
riverctl map normal $meta+Control F toggle-fullscreen
# Mod+F to toggle float
riverctl map normal $meta+Shift Space toggle-float

# Mod+{Up,Right,Down,Left} to change layout orientation
riverctl map normal $meta Up layout rivercarro top
riverctl map normal $meta Right layout rivercarro right
riverctl map normal $meta Down layout rivercarro bottom
riverctl map normal $meta Left layout rivercarro left

riverctl focus-follows-cursor normal
riverctl set-cursor-warp on-output-change
riverctl hide-cursor when-typing enabled

# Mod+S to change to Full layout
riverctl map normal $meta S layout full

# input settings
riverctl set-repeat 35 300
riverctl input 1133:49291:Logitech_G502_HERO_Gaming_Mouse accel-profile flat

# Set app-ids of views which should float
# riverctl float-filter-add "float"
# riverctl float-filter-add "popup"

# keyboard
riverctl input pointer-1133-49291-Logitech_G502_HERO_Gaming_Mouse accel-profile flat

riverctl background-color 0x000000
riverctl border-color-focused 0xfabd2f
riverctl border-color-unfocused 0x665c54
riverctl border-color-urgent 0xfb4934

riverctl default-layout rivercarro
rivercarro -inner-gaps 6 -outer-gaps 0 -main-ratio 0.5 &

riverctl send-layout-cmd rivercarro "main-location left"
riverctl focus-output next
riverctl send-layout-cmd rivercarro "main-location top"
riverctl focus-output next
